/**
 * basis-rs C bindings
 *
 * High-performance Parquet read/write operations.
 * Generated by cbindgen - do not modify manually.
 */


#ifndef BASIS_RS_H
#define BASIS_RS_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/**
 * Error codes returned by FFI functions.
 */
#define BASIS_OK 0

#define BASIS_ERR_NULL_PTR -1

#define BASIS_ERR_INVALID_UTF8 -2

#define BASIS_ERR_IO -3

#define BASIS_ERR_COLUMN_NOT_FOUND -4

#define BASIS_ERR_TYPE_MISMATCH -5

#define BASIS_ERR_POLARS -6

/**
 * Opaque handle to a DataFrame.
 */
typedef struct BasisDataFrame BasisDataFrame;

/**
 * Result of reading an Int64 column.
 */
typedef struct BasisInt64Column {
  int64_t *data;
  size_t len;
} BasisInt64Column;

/**
 * Result of reading a Float64 column.
 */
typedef struct BasisFloat64Column {
  double *data;
  size_t len;
} BasisFloat64Column;

/**
 * Result of reading a String column.
 */
typedef struct BasisStringColumn {
  char **data;
  size_t len;
} BasisStringColumn;

/**
 * Result of reading a Bool column.
 */
typedef struct BasisBoolColumn {
  bool *data;
  size_t len;
} BasisBoolColumn;

/**
 * Get the last error message. Returns NULL if no error.
 * The returned string is valid until the next FFI call.
 */
 const char *basis_get_last_error(void) ;

/**
 * Clear the last error.
 */
 void basis_clear_error(void) ;

/**
 * Read a Parquet file and return a DataFrame handle.
 * Returns NULL on error. Use `basis_get_last_error()` for details.
 */
 struct BasisDataFrame *basis_parquet_read(const char *path) ;

/**
 * Write a DataFrame to a Parquet file.
 * Returns BASIS_OK on success, negative error code on failure.
 */
 int basis_parquet_write(struct BasisDataFrame *df, const char *path) ;

/**
 * Create a new empty DataFrame.
 */
 struct BasisDataFrame *basis_df_new(void) ;

/**
 * Free a DataFrame handle.
 */
 void basis_df_free(struct BasisDataFrame *df) ;

/**
 * Get the number of rows in the DataFrame.
 */
 size_t basis_df_height(const struct BasisDataFrame *df) ;

/**
 * Get the number of columns in the DataFrame.
 */
 size_t basis_df_width(const struct BasisDataFrame *df) ;

/**
 * Get an Int64 column by name.
 * The caller must free the returned data with `basis_int64_column_free`.
 */

int basis_df_get_int64_column(const struct BasisDataFrame *df,
                              const char *name,
                              struct BasisInt64Column *out)
;

/**
 * Free an Int64Column's data.
 */
 void basis_int64_column_free(struct BasisInt64Column *col) ;

/**
 * Get a Float64 column by name.
 * The caller must free the returned data with `basis_float64_column_free`.
 */

int basis_df_get_float64_column(const struct BasisDataFrame *df,
                                const char *name,
                                struct BasisFloat64Column *out)
;

/**
 * Free a Float64Column's data.
 */
 void basis_float64_column_free(struct BasisFloat64Column *col) ;

/**
 * Get a String column by name.
 * The caller must free the returned data with `basis_string_column_free`.
 */

int basis_df_get_string_column(const struct BasisDataFrame *df,
                               const char *name,
                               struct BasisStringColumn *out)
;

/**
 * Free a StringColumn's data.
 */
 void basis_string_column_free(struct BasisStringColumn *col) ;

/**
 * Add an Int64 column to the DataFrame.
 */

int basis_df_add_int64_column(struct BasisDataFrame *df,
                              const char *name,
                              const int64_t *data,
                              size_t len)
;

/**
 * Add a Float64 column to the DataFrame.
 */

int basis_df_add_float64_column(struct BasisDataFrame *df,
                                const char *name,
                                const double *data,
                                size_t len)
;

/**
 * Add a String column to the DataFrame.
 */

int basis_df_add_string_column(struct BasisDataFrame *df,
                               const char *name,
                               const char *const *data,
                               size_t len)
;

/**
 * Add a Bool column to the DataFrame.
 */

int basis_df_add_bool_column(struct BasisDataFrame *df,
                             const char *name,
                             const bool *data,
                             size_t len)
;

/**
 * Get a Bool column by name.
 * The caller must free the returned data with `basis_bool_column_free`.
 */

int basis_df_get_bool_column(const struct BasisDataFrame *df,
                             const char *name,
                             struct BasisBoolColumn *out)
;

/**
 * Free a BoolColumn's data.
 */
 void basis_bool_column_free(struct BasisBoolColumn *col) ;

#endif  /* BASIS_RS_H */
